DeployTest1

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -18,7 +18,7 @@ jobs:
     steps:
       - name: Checkout code
         uses: actions/checkout@v3
-      
+
       - name: Set up JDK 21
         uses: actions/setup-java@v3
         with:
@@ -45,9 +45,20 @@ jobs:
         env:
           SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
         run: |
-          mkdir -p $HOME/.ssh || sudo mkdir -p /home/runner/.ssh
+          # Отладка окружения
+          echo "User: $(whoami)"
+          echo "Home directory: $HOME"
+          ls -ld $HOME || echo "Home directory not found"
+
+          # Создание .ssh (для разных систем)
+          mkdir -p $HOME/.ssh || sudo mkdir -p /home/runner/.ssh || sudo mkdir -p /Users/runner/.ssh
+
+          # Запись приватного SSH-ключа
           echo "$SSH_PRIVATE_KEY" > $HOME/.ssh/id_rsa
           chmod 600 $HOME/.ssh/id_rsa
+
+          # Добавление сервера в known_hosts
           ssh-keyscan 192.168.111.128 >> $HOME/.ssh/known_hosts
+          
+          # Деплой на сервер
           ssh user@192.168.111.128 'bash ~/deploy.sh'
-      
